version: "3.9"

services:
    deno:
        container_name: deno-blog-bot
        image: deno
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "8000:8000" 