# fly.toml app configuration file generated for funk-bot-blog on 2023-07-01T21:40:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "funk-bot-blog"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true
  cmd = ["run", "-A", "./main.ts"]

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  tcp_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
